version: '3'
services:
    consul-server:
        image: consul
        container_name: consul-server
        environment:
            - consul_bind_interface=eth0
            - consul_client_interface=eth0
        ports:
            - "8500:8500"
            - "8600:8600"
        networks:
            - local
        # command: "-dev -ui"
        
    # app:
        # image: consultest
        # container_name: app
        # build:
            # context: "D:/Projects/ConsulTest"
            # dockerfile: ConsulTest/Dockerfile
        # ports:
            # - "1234:1234"
        # depends_on:
            # - consul
            
networks:
    local:
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: "172.19.0.0/16"
        
        