version: '3'
services:
    consul:
        image: consul
        container_name: consul-server
        environment:
            - consul_bind_interface=eth0
            - consul_client_interface=eth0
        ports:
            - "8500:8500"
            - "8600:8600"
        networks:
            - local
        
    host:
        image: consultest
        container_name: host
        build:
            context: "D:/Projects/ConsulTest"
            dockerfile: ConsulTest/dockerfile
        ports:
            - "1234:1234"
        networks:
            - local
        depends_on:
            - consul
            
    client:
        image: consultest.client
        container_name: client
        build:
            context: "D:/Projects/ConsulTest"
            dockerfile: ConsulTest.Client/Dockerfile
        ports:
            - "1235:1235"
        networks:
            - local
        depends_on:
            - host

networks:
    local:
        driver: bridge
        ipam:
          driver: default
          config:
          - subnet: "172.19.0.0/16"
        
        
