version: '3'
services:
    consul:
        image: consul
        container_name: consul
        environment:
            - CONSUL_BIND_INTERFACE=eth0
            - CONSUL_CLIENT_INTERFACE=eth0
        ports:
            - "8500:8500"
            - "8600:8600"
        command: "agent -server -ui"
        expose:
            - "8500"
        networks:
            - "app-network"
    app:
        image: consultest
        container_name: app
        build:
            context: "D:/Projects/ConsulTest"
            dockerfile: ConsulTest/Dockerfile
        ports:
            - "1234:1234"
        depends_on:
            - consul
        networks:
            - "app-network"
networks:
    "app-network":
        
        